#!/usr/bin/env bash
#
# install-hooks.sh — Install git hooks for the devflow-claude repository
#
# Wires scripts/pre-commit-hook.sh into .git/hooks/pre-commit.
# Safe to run multiple times; will not overwrite an existing non-devflow hook.

set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK_TARGET="$REPO_ROOT/.git/hooks/pre-commit"
HOOK_SOURCE="$REPO_ROOT/scripts/pre-commit-hook.sh"
MARKER="# devflow-claude-hook"

info() { printf "${GREEN}✔${NC}  %s\n" "$1"; }
warn() { printf "${YELLOW}⚠${NC}  %s\n" "$1" >&2; }
err()  { printf "${RED}✖${NC}  %s\n" "$1" >&2; }

if [[ ! -d "$REPO_ROOT/.git" ]]; then
  err "Not a git repository: $REPO_ROOT"
  exit 1
fi

if [[ ! -f "$HOOK_SOURCE" ]]; then
  err "Hook source not found: $HOOK_SOURCE"
  exit 1
fi

# Check for existing hook
if [[ -f "$HOOK_TARGET" ]]; then
  if grep -q "$MARKER" "$HOOK_TARGET" 2>/dev/null; then
    info "DevFlow pre-commit hook already installed, updating..."
  else
    warn "Existing pre-commit hook found that was not installed by DevFlow."
    warn "Please manually integrate scripts/pre-commit-hook.sh into your hook."
    exit 1
  fi
fi

# Write the hook
cat > "$HOOK_TARGET" <<HOOK
#!/usr/bin/env bash
$MARKER
# Auto-generated by scripts/install-hooks.sh — do not edit manually
exec "$HOOK_SOURCE" "\$@"
HOOK

# Note: The hook file needs to be executable. If chmod is unavailable,
# git should still execute hooks from .git/hooks/ by default.
# Attempt to set executable bit:
if command -v chmod &>/dev/null; then
  chmod +x "$HOOK_TARGET" 2>/dev/null || true
fi

info "Pre-commit hook installed: $HOOK_TARGET"
