source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "sqlite3", "~> 2.0"
gem "puma", "~> 6.4"
gem "turbo-rails", "~> 2.0"
gem "stimulus-rails", "~> 1.3"
gem "propshaft", "~> 1.0"
gem "importmap-rails", "~> 2.0"
gem "jbuilder", "~> 2.12"
gem "midi-smtp-server", "~> 3.2"
gem "mail", "~> 2.8"

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
